products_index:
    path:     /
    defaults: { _controller: "JmnProductBundle:Products:index" }
    methods:  GET
products_show:
    path:     /{id}/show
    defaults: { _controller: "JmnProductBundle:Products:show" }
    methods:  GET
products_new:
    path:     /new
    defaults: { _controller: "JmnProductBundle:Products:new" }
    methods:  [GET, POST]
products_edit:
    path:     /{id}/edit
    defaults: { _controller: "JmnProductBundle:Products:edit" }
    methods:  [GET, POST]
products_delete:
    path:     /{id}/delete
    defaults: { _controller: "JmnProductBundle:Products:delete" }
    methods:  DELETE
products_search:
    path:  /search/
    defaults: { _controller: "JmnProductBundle:Products:search" }
    methods:  [GET, POST]
